using System.Collections.Generic;
using System.Linq;

namespace AIRsLight.ClashOfRim.Protocol;

public static class ProtocolContractManifest
{
    public static IReadOnlyList<ProtocolEndpointDescriptor> Endpoints { get; } =
        new[]
        {
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ServerHello,
                "/server/hello",
                requiresIdempotencyKey: false,
                requiresUserId: false,
                requiresColonyId: false,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.Login,
                "/session/login",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.StreamSession,
                "/session/stream",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.MaintainPresence,
                "/session/presence",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.Logout,
                "/session/logout",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ChangeOfflinePassword,
                "/session/password",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ListPlayers,
                "/players/list",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ListAchievements,
                "/achievements/list",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.WaitForEvents,
                "/events/wait",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.PullPendingEvents,
                "/events/pending",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.PullEventDetails,
                "/events/details",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.UploadSnapshot,
                "/snapshots/upload",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.DownloadLatestSnapshot,
                "/snapshots/latest",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.DownloadLatestSnapshotPayload,
                "/snapshots/latest/payload",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ConfirmEventApplication,
                "/events/confirm-application",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ConfirmEventApplications,
                "/events/confirm-applications",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ReportEventApplicationFailure,
                "/events/application-failure",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateGift,
                "/events/gifts",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateGiftWithSnapshot,
                "/events/gifts/create-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RejectGift,
                "/events/gifts/reject",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.StorePawnPackage,
                "/pawns/packages/store",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.GetPawnPackage,
                "/pawns/packages/get",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.StoreThingPackage,
                "/things/packages/store",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.GetThingPackage,
                "/things/packages/get",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.QuoteTradeOrderFee,
                "/events/trades/quote-fee",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateTradeOrder,
                "/events/trades",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateTradeOrderWithSnapshot,
                "/events/trades/create-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ListTradeOrders,
                "/events/trades/market",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.AcceptTradeOrder,
                "/events/trades/accept",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OfflinePending),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.FulfillTradeOrder,
                "/events/trades/fulfill",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.FulfillTradeOrderWithSnapshot,
                "/events/trades/fulfill-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CancelTradeOrder,
                "/events/trades/cancel",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CompleteTradeOrder,
                "/events/trades/complete",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ListServerShop,
                "/shop/list",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.UpsertServerShopListing,
                "/shop/admin/upsert",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RemoveServerShopListing,
                "/shop/admin/remove",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.PurchaseServerShopListingWithSnapshot,
                "/shop/purchase-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.PrepareRaid,
                "/events/raids/prepare",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateRaid,
                "/events/raids",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateRaidWithSnapshot,
                "/events/raids/create-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateDiplomacyEvent,
                "/events/diplomacy",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RespondDiplomacyEvent,
                "/events/diplomacy/respond",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateSupportPawn,
                "/events/support-pawns",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateSupportPawnWithSnapshot,
                "/events/support-pawns/create-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RejectSupportPawn,
                "/events/support-pawns/reject",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.FinishSupportPawn,
                "/events/support-pawns/finish",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.SyncWorldMapMarkers,
                "/world/markers",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: false,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.SyncRuntimeWorldObjects,
                "/world/runtime-objects",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.PrepareWorldSession,
                "/world/session",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.GetWorldConfiguration,
                "/world/configuration/current",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.SubmitWorldConfiguration,
                "/world/configuration",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.UploadWorldSubstrate,
                "/world/configuration/substrate",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.DownloadWorldSubstrate,
                "/world/configuration/substrate/download",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.SubmitWorldFeatureNames,
                "/world/configuration/feature-names",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RegisterPlayerColonySites,
                "/world/colony-sites",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.PreflightColonyRelocation,
                "/world/colony-sites/relocation/preflight",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ConfirmColonyRelocation,
                "/world/colony-sites/relocation/confirm",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.AbandonPlayerColony,
                "/world/colony-sites/abandon",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.GetAdminBaselineRequirements,
                "/admin/baseline/requirements",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.SubmitAdminBaseline,
                "/admin/baseline",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.GetBankStatus,
                "/bank/status",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateBankLoanWithSnapshot,
                "/bank/loans/create-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.CreateBankLoan,
                "/bank/loans",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RepayBankLoan,
                "/bank/loans/repay",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RepayBankLoanWithSnapshot,
                "/bank/loans/repay-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RepayBankDebt,
                "/bank/debts/repay",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.RepayBankDebtWithSnapshot,
                "/bank/debts/repay-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.QuoteMercenary,
                "/mercenaries/quote",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.QuoteMercenaryGuard,
                "/mercenaries/guards/quote",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.HireMercenary,
                "/mercenaries/hire",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.HireMercenaryWithSnapshot,
                "/mercenaries/hire-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.HireMercenaryGuardWithSnapshot,
                "/mercenaries/guards/hire-with-snapshot",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ReportMercenaryIncident,
                "/mercenaries/incidents",
                requiresIdempotencyKey: true,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: true,
                serverMustValidateSnapshot: true,
                ProtocolDeliverySemantics.RequiresSnapshotConfirmation),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.SendChatMessage,
                "/chat/send",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ListChatMessages,
                "/chat/list",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.OverrideCompatibilityBaseline,
                "/compatibility/baseline/override",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.AdminStatus,
                "/admin/status",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.AdminUpdateConfiguration,
                "/admin/configuration",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.AdminAction,
                "/admin/action",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: true,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.OnlineImmediate),
            new ProtocolEndpointDescriptor(
                ProtocolMessageKind.ServerNotification,
                "/notifications",
                requiresIdempotencyKey: false,
                requiresUserId: true,
                requiresColonyId: false,
                requiresSnapshotId: false,
                serverMustValidateSnapshot: false,
                ProtocolDeliverySemantics.ServerNotification)
        };

    public static ProtocolEndpointDescriptor Find(ProtocolMessageKind kind)
    {
        return Endpoints.Single(endpoint => endpoint.Kind == kind);
    }
}
